### ISSUE TITLE
Error: INVALID_APP_ID (Android)

### ISSUE THREAD

**Issue by TomFevrier** [cjam/react-native-spotify-remote#54] opened 2020-06-19 18:01 UTC
Hello there!

When I try to authenticate, I get an `INVALID_APP_ID` error...
I don't understand why: my server (for token swap and refresh) is correctly set up, and I have added the package name and Android SHA1 key to my app on the Spotify dashboard (as stated in the documentation).

Any idea about what might go wrong?

Also, is there a way to connect to the Remote SDK without using the Auth SDK at all? I have already implemented my own logic for dealing with access tokens and refreshing them, and it would be great to be able to connect directly from a valid access token.

Thank you!

**Comment by Cal-JChapman** [comment] 2020-06-20 12:22
I'm having the same problem lol, I'm using both my debug and release SHA-1 keys and the android package name on my spotify dashboard (am I correct in assuming you need both a debug and release key to connect?)

**Comment by alexdanielyan** [comment] 2020-07-03 10:12
Same error

**Comment by cjam** [comment] 2020-07-09 12:36
Hey sorry for the long delay on this.  I haven't been able to reproduce this in my example, though I have seen it in the past in my own work on this.  It has generally been an issue with the setup of my app in terms of app id and the application registration with spotify.  Were you able to get the example app working?

**Comment by uptotec** [comment] 2020-07-29 03:52
I have the same problem here
![Screenshot_20200729-055047_spoticount.jpg](https://user-images.githubusercontent.com/38630967/88754690-9cbdbc80-d15f-11ea-95d2-aa5c147c0b79.jpg)

**Comment by uptotec** [comment] 2020-07-29 04:32
I guess the problem is the express server does not receive any requests from the app

**Comment by uptotec** [comment] 2020-07-29 05:01
I finally found a solution. the solution is to add the full package name and the SHA1 fingerprint in the spotify app dashboard settings under name 'Android Packages' you will find the full package name in the android/app/src/main/java/[...]/MainActivity.java and you can get the SHA1 fingerprint by running **./gradlew signingReport** in the android folder

**Comment by cjam** [comment] 2020-09-06 23:02
closing as it seems this was solved

**Closed by cjam** 2020-09-06 23:02 UTC
